const mongoose = require('mongoose');

const lorryReceiptSchema = new mongoose.Schema({
    lrNumber:{type:String, unquie :true},
    lrDate: { type: Date, required: true },
    from: { type: String, required: true },
    to: { type: String, required: true },
    lorryNumber: { type: String },
    driversContact: { type: String },
    loadType: { type: String, default: 'Full' },
    consignor: { type: String },
    consignee: { type: String },
    freightPayableCompany: { type: String },
    invoiceValue: { type: String },
    vehicleNo: {type:String},
    driversNo:{type:String},
    paymentMode: { type: String },
    billingBranch: { type: String },
    collectionType: { type: String },
    deliveryType: { type: String },
    itemType: { type: String, default: 'General' },
    description: { type: String },
    invoiceString: { type: String },
    quantity: { type: String },
    unit: { type: String },
    rate: { type: String },
    actualWeight: { type: String },
    chargeableWeight: { type: String },
    totalAmount: { type: String },
    remarks: { type: String },
    freight: { type: String },
    surCharges: { type: String },
    stasticalCharges: { type: String },
    hamali: { type: String },
    dcCharges: { type: String },
    ddCharges: { type: String },
    holting: { type: String },
    other: { type: String },
    total: { type: String }
});

module.exports = mongoose.model('LorryReceipt', lorryReceiptSchema);
