const mongoose = require('mongoose');

const lorryReceiptSchema = new mongoose.Schema({
    lrString:{type:String, unquie :true},
    lrDate: { type: Date, required: true },
    from: { type: String, required: true },
    to: { type: String, required: true },
    lorryString: { type: String },
    driversContact: { type: String },
    loadType: { type: String, default: 'Full' },
    consignor: { type: String },
    consignee: { type: String },
    freightPayableCompany: { type: String },
    invoiceValue: { type: String, default: 'inv' },
    paymentMode: { type: String, default: 'TBB' },
    billingBranch: { type: String, default: 'Kolhapur' },
    collectionType: { type: String, default: 'DC' },
    deliveryType: { type: String, default: 'DD' },
    itemType: { type: String, default: 'General' },
    description: { type: String },
    invoiceString: { type: String },
    quantity: { type: String },
    unit: { type: String, default: 'Nos' },
    rate: { type: String },
    actualWeight: { type: String },
    chargeableWeight: { type: String },
    totalAmount: { type: String },
    remarks: { type: String },
    freight: { type: String },
    surCharges: { type: String },
    stasticalCharges: { type: String },
    hamali: { type: String },
    dcCharges: { type: String },
    ddCharges: { type: String },
    holting: { type: String },
    other: { type: String },
    total: { type: String }
});

module.exports = mongoose.model('LorryReceipt', lorryReceiptSchema);
